travis: license check does not fail but report issues
Master branch contains lot of missing SPDX identifiers, we will clean them up but this will take some time. In the meantime, we should not increase the license missing files. Each PR will report if there is no license issue or positive number reported as Github status. Travis won't fail if there are issues. This will highlight the issues that anyone can fix.

As soon as master is clean, we can fix set_status and revert part of this commit.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -73,7 +73,20 @@ matrix:
               | ( grep -v '^tools/test/toolchains/api_test.py') \
               | while read file; do cp --parents "${file}" SCANCODE; done
         - scancode -l --json-pp scancode.json SCANCODE
+        - python ./tools/test/travis-ci/scancode-evaluate.py -f scancode.json || true
+      after_success:
         - python ./tools/test/travis-ci/scancode-evaluate.py -f scancode.json
+        - retval=$?
+        - |
+          if [ $retval == 0 ]; then
+              echo "License check OK";
+            else
+              echo "License check failed, please review license issues found";
+              STATUSM="Needs review, ${retval} license issues found";
+              set_status "success" "$STATUSM";
+          fi
+
+
 
     - <<: *basic-vm
       name: "include check"
