Bring python packages into the mbed-os source (#192)
* Initial import of python packages

* Move tests to subfolder, use tests in generate_configuration.cmake

* Bring python packages into the source tree instead of needing to be installed separately

* Use python3

* Just use distro default python

* Install all the requirements with apt-get

* unittests is part of Python now

* Add appdirs, set python version

* Add some missing dependencies

* Add more packages

* Add requirements.apt.txt files, fix relative paths with scancode_evaluate.py

* Fix return code handling for license scan errors

* ok let's try that again, also improve error output from scancode evaluate

* Add missing license headers

diff --git a/.github/workflows/basic_checks.yml b/.github/workflows/basic_checks.yml
--- a/.github/workflows/basic_checks.yml
+++ b/.github/workflows/basic_checks.yml
@@ -25,8 +25,11 @@ jobs:
       - 
         name: install dependencies
         shell: bash
+        # TODO scancode 32.0 introduced significant breaking changes to the license
+        # detection output format: https://github.com/nexB/scancode-toolkit/releases/tag/v32.0.0
+        # Need to update Mbed's scripts for the new format.
         run: |
-          pip install -U scancode-toolkit "click>=7,<8"
+          pip install -U "scancode-toolkit<32.0" "click>=7,<8"
 
       - 
         name: license check 
@@ -43,10 +46,14 @@ jobs:
             | while read file; do cp --parents "${file}" SCANCODE; done
           ls SCANCODE
           scancode -l --json-pp scancode.json SCANCODE
-          python ./tools/test/ci/scancode-evaluate.py scancode.json || true
-          cat scancode-evaluate.log
-          COUNT=$(cat scancode-evaluate.log | grep 'File:' | grep -v 'SPDX' | wc -l) || true
-          if [ $COUNT = 0 ]; then
+          cd tools/python
+          
+          # Run the evaluation script, which may fail, and save its exit code.
+          EVALUATE_EXITCODE=0
+          python -m scancode_evaluate.scancode_evaluate ../../scancode.json || EVALUATE_EXITCODE=$?
+          
+          cat scancode_evaluate.log
+          if [ "$EVALUATE_EXITCODE" = 0 ]; then
             echo "License check OK";
             true;
           else
@@ -158,25 +165,18 @@ jobs:
         name: Checkout repo
         uses: actions/checkout@v3
 
-
-      - uses: actions/setup-python@v2
-        with:
-          python-version: '3.7'
-
       -
         name: install dependencies
         run: |
-          pip install -r tools/requirements.txt 
-          pip install -r tools/test/requirements.txt
+          xargs sudo apt-get install -y < tools/requirements.apt.txt
+          xargs sudo apt-get install -y < tools/python/python_tests/requirements.apt.txt
 
       -
-        name: pytest
+        name: Python Tests
         run: |
-          set -x
-          coverage run -a -m pytest tools/test
-          python tools/test/pylint.py
-          coverage run -a tools/project.py -S | sed -n '/^Total/p'
-          coverage html
+          cd tools/python
+          ./run_python_tests.sh
+
 
   pin-validation:
     runs-on: ubuntu-latest
